name: Tests

on:
    push:
        branches: [ main, develop ]
    pull_request:
        types: [ opened, synchronize, ready_for_review, labeled ]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Run Unit Tests
              run: |
                make unit-test
            - name: Run E2E Tests
              run: |
                make e2e-test